"""empty message

Revision ID: 2f1d91f8109a
Revises: None
Create Date: 2016-04-10 18:25:36.766550

"""

# revision identifiers, used by Alembic.
revision = '2f1d91f8109a'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('business', sa.Column('accountnumber', sa.String(length=64), nullable=True))
    op.add_column('business', sa.Column('bsb', sa.String(length=64), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('business', 'bsb')
    op.drop_column('business', 'accountnumber')
    ### end Alembic commands ###
