"""empty message

Revision ID: 3b17a14d302c
Revises: 2f1d91f8109a
Create Date: 2016-07-19 13:45:22.158623

"""

# revision identifiers, used by Alembic.
revision = '3b17a14d302c'
down_revision = '2f1d91f8109a'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('client', sa.Column('abn', sa.String(length=64), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('client', 'abn')
    ### end Alembic commands ###
